use ca;

insert into pfx_countries (code, title) values ('AD','Andorra'),('AE','United Arab Emirates'),('AF','Afghanistan'),('AG','Antigua & Barbuda'),('AI','Anguilla'),('AL','Albania');
insert into pfx_countries (code, title) values ('AM','Armenia'),('AN','Netherlands Antilles'),('AO','Angola'),('AQ','Antarctica'),('AR','Argentina'),('AS','American Samoa'),('AT','Austria');
insert into pfx_countries (code, title) values ('AU','Australia'),('AW','Aruba'),('AZ','Azerbaijan'),('BA','Bosnia and Herzegovina'),('BB','Barbados'),('BD','Bangladesh'),('BE','Belgium');
insert into pfx_countries (code, title) values ('BF','Burkina Faso'),('BG','Bulgaria'),('BH','Bahrain'),('BI','Burundi'),('BJ','Benin'),('BM','Bermuda'),('BN','Brunei Darussalam');
insert into pfx_countries (code, title) values ('BO','Bolivia'),('BR','Brazil'),('BS','Bahama'),('BT','Bhutan'),('BV','Bouvet Island'),('BW','Botswana'),('BY','Belarus'),('BZ','Belize');
insert into pfx_countries (code, title) values ('CA','Canada'),('CC','Cocos (Keeling) Islands'),('CF','Central African Republic'),('CG','Congo'),('CH','Switzerland'),('CI','Cote D''ivoire (Ivory Coast)');
insert into pfx_countries (code, title) values ('CK','Cook Iislands'),('CL','Chile'),('CM','Cameroon'),('CN','China'),('CO','Colombia'),('CR','Costa Rica'),('CU','Cuba'),('CV','Cape Verde');
insert into pfx_countries (code, title) values ('CX','Christmas Island'),('CY','Cyprus'),('CZ','Czech Republic'),('DE','Germany'),('DJ','Djibouti'),('DK','Denmark'),('DM','Dominica');
insert into pfx_countries (code, title) values ('DO','Dominican Republic'),('DZ','Algeria'),('EC','Ecuador'),('EE','Estonia'),('EG','Egypt'),('EH','Western Sahara'),('ER','Eritrea');
insert into pfx_countries (code, title) values ('ES','Spain'),('ET','Ethiopia'),('FI','Finland'),('FJ','Fiji'),('FK','Falkland Islands (Malvinas)'),('FM','Micronesia'),('FO','Faroe Islands');
insert into pfx_countries (code, title) values ('FR','France'),('FX','France, Metropolitan'),('GA','Gabon'),('GB','United Kingdom (Great Britain)'),('GD','Grenada'),('GE','Georgia');
insert into pfx_countries (code, title) values ('GF','French Guiana'),('GH','Ghana'),('GI','Gibraltar'),('GL','Greenland'),('GM','Gambia'),('GN','Guinea'),('GP','Guadeloupe'),('GQ','Equatorial Guinea');
insert into pfx_countries (code, title) values ('GR','Greece'),('GS','South Georgia and the South Sandwich Islands'),('GT','Guatemala'),('GU','Guam'),('GW','Guinea-Bissau'),('GY','Guyana');
insert into pfx_countries (code, title) values ('HK','Hong Kong'),('HM','Heard & McDonald Islands'),('HN','Honduras'),('HR','Croatia'),('HT','Haiti'),('HU','Hungary'),('ID','Indonesia');
insert into pfx_countries (code, title) values ('IE','Ireland'),('IL','Israel'),('IN','India'),('IO','British Indian Ocean Territory'),('IQ','Iraq'),('IR','Islamic Republic of Iran');
insert into pfx_countries (code, title) values ('IS','Iceland'),('IT','Italy'),('JM','Jamaica'),('JO','Jordan'),('JP','Japan'),('KE','Kenya'),('KG','Kyrgyzstan'),('KH','Cambodia'),('KI','Kiribati');
insert into pfx_countries (code, title) values ('KM','Comoros'),('KN','St. Kitts and Nevis'),('KP','Democratic People''s Republic of Korea'),('KR','Republic of Korea'),('KW','Kuwait');
insert into pfx_countries (code, title) values ('KY','Cayman Islands'),('KZ','Kazakhstan'),('LA','Lao People''s Democratic Republic'),('LB','Lebanon'),('LC','Saint Lucia'),('LI','Liechtenstein');
insert into pfx_countries (code, title) values ('LK','Sri Lanka'),('LR','Liberia'),('LS','Lesotho'),('LT','Lithuania'),('LU','Luxembourg'),('LV','Latvia'),('LY','Libyan Arab Jamahiriya');
insert into pfx_countries (code, title) values ('MA','Morocco'),('MC','Monaco'),('MD','Republic of Moldova'),('MG','Madagascar'),('MH','Marshall Islands'),('ML','Mali'),('MM','Myanmar');
insert into pfx_countries (code, title) values ('MN','Mongolia'),('MO','Macau'),('MP','Northern Mariana Islands'),('MQ','Martinique'),('MR','Mauritania'),('MS','Monserrat'),('MT','Malta');
insert into pfx_countries (code, title) values ('MU','Mauritius'),('MV','Maldives'),('MW','Malawi'),('MX','Mexico'),('MY','Malaysia'),('MZ','Mozambique'),('NA','Nambia'),('NC','New Caledonia');
insert into pfx_countries (code, title) values ('NE','Niger'),('NF','Norfolk Island'),('NG','Nigeria'),('NI','Nicaragua'),('NL','Netherlands'),('NO','Norway'),('NP','Nepal'),('NR','Nauru');
insert into pfx_countries (code, title) values ('NU','Niue'),('NZ','New Zealand'),('OM','Oman'),('PA','Panama'),('PE','Peru'),('PF','French Polynesia'),('PG','Papua New Guinea'),('PH','Philippines');
insert into pfx_countries (code, title) values ('PK','Pakistan'),('PL','Poland'),('PM','St. Pierre & Miquelon'),('PN','Pitcairn'),('PR','Puerto Rico'),('PT','Portugal'),('PW','Palau'),('PY','Paraguay');
insert into pfx_countries (code, title) values ('QA','Qatar'),('RE','Reunion'),('RO','Romania'),('RU','Russian Federation'),('RW','Rwanda'),('SA','Saudi Arabia'),('SB','Solomon Islands'),('SC','Seychelles');
insert into pfx_countries (code, title) values ('SD','Sudan'),('SE','Sweden'),('SG','Singapore'),('SH','St. Helena'),('SI','Slovenia'),('SJ','Svalbard & Jan Mayen Islands'),('SK','Slovakia'),('RS','Serbia');
insert into pfx_countries (code, title) values ('SL','Sierra Leone'),('SM','San Marino'),('SN','Senegal'),('SO','Somalia'),('SR','Suriname'),('ST','Sao Tome & Principe'),('SV','El Salvador');
insert into pfx_countries (code, title) values ('SY','Syrian Arab Republic'),('SZ','Swaziland'),('TC','Turks & Caicos Islands'),('TD','Chad'),('TF','French Southern Territories'),('TG','Togo');
insert into pfx_countries (code, title) values ('TH','Thailand'),('TJ','Tajikistan'),('TK','Tokelau'),('TM','Turkmenistan'),('TN','Tunisia'),('TO','Tonga'),('TP','East Timor'),('TR','Turkey');
insert into pfx_countries (code, title) values ('TT','Trinidad & Tobago'),('TV','Tuvalu'),('TW','Taiwan'),('TZ','United Republic of Tanzania'),('UA','Ukraine'),('UG','Uganda');
insert into pfx_countries (code, title) values ('UM','United States Minor Outlying Islands'),('US','United States of America'),('UY','Uruguay'),('UZ','Uzbekistan'),('VA','Vatican City State (Holy See)');
insert into pfx_countries (code, title) values ('VC','St. Vincent & the Grenadines'),('VE','Venezuela'),('VG','British Virgin Islands'),('VI','United States Virgin Islands'),('VN','Viet Nam');
insert into pfx_countries (code, title) values ('VU','Vanuatu'),('WF','Wallis & Futuna Islands'),('WS','Samoa'),('YE','Yemen'),('YT','Mayotte'),('YU','Yugoslavia'),('ZA','South Africa');
insert into pfx_countries (code, title) values ('ZM','Zambia'),('ZR','Zaire'),('ZW','Zimbabwe'),('ZZ','Unknown');
